apiVersion: v1
kind: Service
metadata:
  name: tm-api-service
  namespace: <K8S_NAMESPACE>
spec:
  type: ClusterIP
  selector:
    app: tm-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http